### ISSUE TITLE
Hyperparams setting while training on MNIST dataset

### ISSUE THREAD

**Issue by ibei** [eitanrich/torch-mfa#2]
MFA trainning on celebA performed very well
But the one on MNIST is not good.
The NDB/K is large
KL-divergence is large too
Could you share the hyperparameters used in your trial?
Thanks a lot! That would be very helpful!

**Comment by eitanrich** [comment]
The hyper-parameters I used are the ones defined in train.py.
It is indeed possible that the official (TensorFlow) implementation reaches a better model for MNIST because it uses the more expressive MFA model that has a different noise variance per pixel. In MNIST this might be important, since in many pixels the variance is very small and in others very large. Another possible difference is the initialization (random samples instead of K-means).
I didn't test the resulting MNIST model with NDB.
I have updated the readme with the changes from the official implementation and also updated the TODO list. Adding K-means initialization should be quite easy, so I will probably do this first.

**Comment by ibei** [comment]
> The hyper-parameters I used are the ones defined in train.py.
> It is indeed possible that the official (TensorFlow) implementation reaches a better model for MNIST because it uses the more expressive MFA model that has a different noise variance per pixel. In MNIST this might be important, since in many pixels the variance is very small and in others very large. Another possible difference is the initialization (random samples instead of K-means).
> I didn't test the resulting MNIST model with NDB.
> I have updated the readme with the changes from the official implementation and also updated the TODO list. Adding K-means initialization should be quite easy, so I will probably do this first.

Thanks for your reply!
Maybe I miss something important, such as the noise. I have tested many trials for a good result like that in your papers, where the NDB value is small.
Anyway, I will try more. Thanks.
BTW,  it's so great that you release a Pytorch version.

**Comment by ibei** [comment]
> sive MFA model that has a different noise variance p



> The hyper-parameters I used are the ones defined in train.py.
> It is indeed possible that the official (TensorFlow) implementation reaches a better model for MNIST because it uses the more expressive MFA model that has a different noise variance per pixel. In MNIST this might be important, since in many pixels the variance is very small and in others very large. Another possible difference is the initialization (random samples instead of K-means).
> I didn't test the resulting MNIST model with NDB.
> I have updated the readme with the changes from the official implementation and also updated the TODO list. Adding K-means initialization should be quite easy, so I will probably do this first.

Hi, eitanrich,
after adding noise, the NDB test is worse. Actually the generated images are much fuzzy. And the obtained NDB value using syn_data without noise is smaller than that using syn_data with noise.
However, I do agree that using noise is more expressive on MNIST data.
Now what i am doing is using a smaller batch-size (like 128 or 256) instead of 512 or 1000.
512 is easy to cause overfitting.
I will be very appreciated If you have any trick to tell me to train the model on MNIST data.
Thanks!

**Comment by ibei** [comment]
OK, I found my problem. it is because I use a wrong evaluation of NDB.
Now I can get the right NDB value.

**Comment by eitanrich** [comment]
Great! BTW I added an option to use k-means initialization as was done in the original paper. It leads to a slightly different solution (local maxima) that perhaps is better suited to MNIST.
